# -*- coding: utf-8 -*-
"""flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2S_WEa4RgRhlT6NyhFD0urgzHmuirJt
"""

from flask import Flask, render_template, request
import numpy as np
import joblib

app = Flask(__name__)

# Load the trained model
model = joblib.load('heart_failure_prediction_model.pkl')

# Home route
@app.route('/')
def home():
    return render_template('index.html')

# Prediction route
@app.route('/predict', methods=['POST'])
def predict():
    if request.method == 'POST':
        # Get form values
        age = float(request.form['age'])
        cp = float(request.form['creatinine_phosphokinase'])
        ef = float(request.form['ejection_fraction'])
        platelets = float(request.form['platelets'])
        sc = float(request.form['serum_creatinine'])
        ss = float(request.form['serum_sodium'])
        time = float(request.form['time'])

        # Create input array
        features = np.array([[age, cp, ef, platelets, sc, ss, time]])

        # Predict
        prediction = model.predict(features)[0]

        # Map to label
        result = 'DEATH (0)' if prediction == 0 else 'noDEATH (1)'

        return render_template('result.html', prediction=result)


if __name__ == "__main__":
    app.run(debug=True, port=5001)